import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { useTheme } from "@/hooks/useTheme";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // hooks
  const theme = useTheme();

  return (
    <html lang="en" className={theme}>
      <body className={inter.className}>
        <Toaster position="top-center" reverseOrder={false} />
        <Analytics />
        <SpeedInsights />
        {children}
      </body>
    </html>
  );
}
